source 'https://gems.ruby-china.com'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'active_model_serializers'
gem 'api-pagination'
#gem 'bcrypt'
gem 'bcrypt', '~> 3.1.7', platforms: :ruby
gem 'coffee-rails', '~> 4.2'
gem 'figaro'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'jwt'
gem 'kaminari'
gem 'mysql2'
gem 'puma', '~> 3.0'
gem 'qiniu', '>= 6.8.0'
gem 'rack-attack'
gem 'rack-cors', :require => 'rack/cors'
gem 'rails', '~> 5.0.1'
gem 'redis'
gem "sendcloud_client"
gem 'redis-objects'
gem 'rest-client'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem "gon"
gem 'sidekiq'
gem 'wechat'
gem 'whenever', :require => false
gem 'wx_pay'
gem 'uuid'
gem 'rails-controller-testing'
gem 'agi_scaffold', :git => 'https://code.aliyun.com/agideo/agi_scaffold.git'
# 单点登录
gem 'rubycas-client', path: './vendor/gems/rubycas-client-2.3.14' #git: 'git://github.com/mdsol/rubycas-client.git' #:git => 'git://github.com/rubycas/rubycas-client.git'
gem 'rubycas-client-rails' #, :git => 'git://github.com/creativecommons/rubycas-client-rails.git'
gem 'activerecord-session_store'


# sidekiq related
gem 'sidekiq'
gem 'sidekiq-scheduler'

gem 'by_star'

# api documents
gem 'swagger-docs'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'byebug', platform: :mri
  gem 'capistrano', "3.8.0"
  gem 'capistrano-bundler', group: :development
  gem 'capistrano-rails'
  gem 'capistrano3-puma'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'capistrano-sidekiq'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
